package com.farkhod.famousbooksapp.enums;

public enum BookGenreEnum {
    ROMANCE,
    THRILLER,
    DETECTIVE,
    MYSTERY,
    HORROR,
    FANTASY,
    SCIENCE_FICTION,
    ADVENTURE,
    HISTORICAL,
    CLASSIC,
    DRAMA,
    POETRY,
    BIOGRAPHY,
    MEMOIR,
    PHILOSOPHY,
    PSYCHOLOGY,
    SELF_DEVELOPMENT,
    BUSINESS,
    SCIENCE,
    TECHNOLOGY,
    RELIGION,
    EDUCATION,
    TRAVEL,
    CHILDREN,
    YOUNG_ADULT,
    OTHER,
}
